### ISSUE TITLE
Set and get stash within entry loop

### ISSUE THREAD

**Issue by wesearl91** [croxton/Stash#152]
How can I set and get stash within the same entry loop.

Can't figure it out for the life of me.

`{exp:stash:parse process="end"}
	{exp:channel:entries channel="products" status="open" limit="10"}
    <div class="item product-overview">
    <img src="http://placehold.it/275x345" alt="New Arrival">
    <div class="product-new-arrival-info">
    <h4 class="product-overview-absoloute-title">{title}</h4>
     {if product_original_price && product_original_price > product_price}
     <span class="product-price"><span class="fa fa-tag"></span> {product_price:plus_tax}</span>
     <del class="product-was-price">{product_original_price:plus_tax}</del>
	 {exp:stash:set name="sale_tag"}<span class="product-sale-tag">Sale</span>{/exp:stash:set}
     {if:else}
     <span class="product-price">{product_price:plus_tax}</span>
     {/if}
	</div>
	{exp:stash:get name="sale_tag" process="end"}
    </div>
	{/exp:channel:entries}
{/exp:stash:parse}`

**Comment by croxton** [comment]
That won't work because the value of 'sale_tag' will change with each iteration of the channel:entries loop, and by adding process="end" you are basically asking to get the last value the variable was set to. It doesn't make any sense because you are assuming that expressionengine tags are being parsed linearly (top to bottom in order on each iteration of the channel entries loop, like PHP or Javascript) but they are are actually parsed recursively - from the outermost "shell" of tags inwards.

Looking at that code I don't see why you need Stash at all, why not just use the channel:entries variables where you want them?

**Comment by wesearl91** [comment]
It was to save having another if statement within the entry loop. I thought
it would be cleaner? Is there a way with stash I can achieve this? stashing
and getting a variable within same loop?

Thanks,

Wes

**Comment by croxton** [comment]
It will be far slower than just using a conditional. EE will parse conditionals in one go, but if you use a Stash tag to get a variable value then for each tag EE must instantiate a new Stash instance to return a value. Much more memory required, so not sensible.

But if you did need to do it you would do something like this:

```
{exp:channel:entries ...}
      {exp:stash:set name="my_variable"}{title}{/exp:stash:set}
      ...
      {exp:stash:get name="my_variable" random}
{/exp:channel:entries}
```

Note the 'random' on the stash:get. That's to stop EE caching the output of the tag the first time it encounters it.

But like I say, don't do this.

**Comment by wesearl91** [comment]
Thank's Mark! So benefical for me to know, I'd never known it would be
slower. I'm not very expereinced in that area, so everything is a learning
curve! I just thought because it looked cleaner to me it would be more
efficient, but that's not the case! Thank you again.

Wes
